// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bartisan_fit
List bartisan_fit(const arma::mat& X, const arma::uvec& has_na, const arma::vec& y, const arma::vec& weights, const arma::mat& offset, const arma::sp_mat& group_probs, std::string family_name, std::string link, List family_opts, List control, List random_spec);
RcppExport SEXP _bartisan_bartisan_fit(SEXP XSEXP, SEXP has_naSEXP, SEXP ySEXP, SEXP weightsSEXP, SEXP offsetSEXP, SEXP group_probsSEXP, SEXP family_nameSEXP, SEXP linkSEXP, SEXP family_optsSEXP, SEXP controlSEXP, SEXP random_specSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type has_na(has_naSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type group_probs(group_probsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type link(linkSEXP);
    Rcpp::traits::input_parameter< List >::type family_opts(family_optsSEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< List >::type random_spec(random_specSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_fit(X, has_na, y, weights, offset, group_probs, family_name, link, family_opts, control, random_spec));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_predict
List bartisan_predict(const arma::mat& X, const std::vector<double>& forest_flat, const std::vector<int>& tree_start, const arma::mat& bandwidth, int num_forest, const std::vector<int>& num_trees, int num_save, bool soft, int gate, const std::vector<int>& iterations);
RcppExport SEXP _bartisan_bartisan_predict(SEXP XSEXP, SEXP forest_flatSEXP, SEXP tree_startSEXP, SEXP bandwidthSEXP, SEXP num_forestSEXP, SEXP num_treesSEXP, SEXP num_saveSEXP, SEXP softSEXP, SEXP gateSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type forest_flat(forest_flatSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type tree_start(tree_startSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< int >::type num_forest(num_forestSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type num_trees(num_treesSEXP);
    Rcpp::traits::input_parameter< int >::type num_save(num_saveSEXP);
    Rcpp::traits::input_parameter< bool >::type soft(softSEXP);
    Rcpp::traits::input_parameter< int >::type gate(gateSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_predict(X, forest_flat, tree_start, bandwidth, num_forest, num_trees, num_save, soft, gate, iterations));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_logdens
arma::mat bartisan_logdens(const arma::vec& y, const arma::vec& weights, const List& eta_draws, std::string family_name, std::string link, List family_opts, const arma::mat& aux);
RcppExport SEXP _bartisan_bartisan_logdens(SEXP ySEXP, SEXP weightsSEXP, SEXP eta_drawsSEXP, SEXP family_nameSEXP, SEXP linkSEXP, SEXP family_optsSEXP, SEXP auxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const List& >::type eta_draws(eta_drawsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type link(linkSEXP);
    Rcpp::traits::input_parameter< List >::type family_opts(family_optsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aux(auxSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_logdens(y, weights, eta_draws, family_name, link, family_opts, aux));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_mnp_probs
arma::cube bartisan_mnp_probs(const List& eta_draws, const arma::mat& sigma, int replicates);
RcppExport SEXP _bartisan_bartisan_mnp_probs(SEXP eta_drawsSEXP, SEXP sigmaSEXP, SEXP replicatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type eta_draws(eta_drawsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type replicates(replicatesSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_mnp_probs(eta_draws, sigma, replicates));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_derivs
List bartisan_derivs(const arma::vec& y, const arma::vec& weights, const List& eta_draws, std::string family_name, std::string link, List family_opts, const arma::mat& aux, int component, bool by_difference, bool blocked);
RcppExport SEXP _bartisan_bartisan_derivs(SEXP ySEXP, SEXP weightsSEXP, SEXP eta_drawsSEXP, SEXP family_nameSEXP, SEXP linkSEXP, SEXP family_optsSEXP, SEXP auxSEXP, SEXP componentSEXP, SEXP by_differenceSEXP, SEXP blockedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const List& >::type eta_draws(eta_drawsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_name(family_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type link(linkSEXP);
    Rcpp::traits::input_parameter< List >::type family_opts(family_optsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type aux(auxSEXP);
    Rcpp::traits::input_parameter< int >::type component(componentSEXP);
    Rcpp::traits::input_parameter< bool >::type by_difference(by_differenceSEXP);
    Rcpp::traits::input_parameter< bool >::type blocked(blockedSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_derivs(y, weights, eta_draws, family_name, link, family_opts, aux, component, by_difference, blocked));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_rpg
Rcpp::NumericVector bartisan_rpg(int n, double b, double c);
RcppExport SEXP _bartisan_bartisan_rpg(SEXP nSEXP, SEXP bSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_rpg(n, b, c));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_rtruncnorm
Rcpp::NumericVector bartisan_rtruncnorm(int n, double lo, double hi);
RcppExport SEXP _bartisan_bartisan_rtruncnorm(SEXP nSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(bartisan_rtruncnorm(n, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// bartisan_optimized
bool bartisan_optimized();
RcppExport SEXP _bartisan_bartisan_optimized() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(bartisan_optimized());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bartisan_bartisan_fit", (DL_FUNC) &_bartisan_bartisan_fit, 11},
    {"_bartisan_bartisan_predict", (DL_FUNC) &_bartisan_bartisan_predict, 10},
    {"_bartisan_bartisan_logdens", (DL_FUNC) &_bartisan_bartisan_logdens, 7},
    {"_bartisan_bartisan_mnp_probs", (DL_FUNC) &_bartisan_bartisan_mnp_probs, 3},
    {"_bartisan_bartisan_derivs", (DL_FUNC) &_bartisan_bartisan_derivs, 10},
    {"_bartisan_bartisan_rpg", (DL_FUNC) &_bartisan_bartisan_rpg, 3},
    {"_bartisan_bartisan_rtruncnorm", (DL_FUNC) &_bartisan_bartisan_rtruncnorm, 3},
    {"_bartisan_bartisan_optimized", (DL_FUNC) &_bartisan_bartisan_optimized, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bartisan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
