# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit a generalized BART model
#'
#' The workhorse behind [genbart()]. Not intended to be called directly: it
#' assumes the design matrix has already been mapped to the unit interval and
#' the response already coerced to the form the requested family expects.
#'
#' @param X design matrix with entries in `[0, 1]`, possibly with `NA`.
#' @param has_na indicator per column of `X` of whether it contains a missing
#'   value. A rule on a column with none is not given a missing-value branch, so
#'   complete data reproduces the sampler exactly as it was.
#' @param y response, coerced by the calling family.
#' @param weights prior weights.
#' @param offset an `H` by `N` matrix of fixed contributions to the additive
#'   predictors.
#' @param group_probs sparse matrix whose columns are predictor groups.
#' @param family_name,link,family_opts the family specification.
#' @param control a list of sampler and prior settings.
#' @return A list of posterior draws and the encoded forests.
#' @keywords internal
.genbart_fit <- function(X, has_na, y, weights, offset, group_probs, family_name, link, family_opts, control, random_spec) {
    .Call(`_genbart_genbart_fit`, X, has_na, y, weights, offset, group_probs, family_name, link, family_opts, control, random_spec)
}

#' Evaluate stored forests at new data
#'
#' @param X design matrix with entries in `[0, 1]`.
#' @param forest_flat,tree_start the encoded forests returned by
#'   `.genbart_fit()`.
#' @param bandwidth a matrix of per-tree bandwidths.
#' @param num_forest,num_trees,num_save dimensions of the stored chain.
#' @param soft whether the decision rules are soft.
#' @param gate which gate the soft rules use; see `GateShape` in `node.h`.
#' @param iterations the zero-based saved iterations to evaluate.
#' @return A list of `num_forest` matrices of additive predictors.
#' @keywords internal
.genbart_predict <- function(X, forest_flat, tree_start, bandwidth, num_forest, num_trees, num_save, soft, gate, iterations) {
    .Call(`_genbart_genbart_predict`, X, forest_flat, tree_start, bandwidth, num_forest, num_trees, num_save, soft, gate, iterations)
}

#' Conditional log density of the outcome at stored posterior draws
#'
#' Evaluates the family's log density for each observation at each posterior
#' draw of the additive predictors, using the nuisance parameters drawn at the
#' same iteration. This is the likelihood contribution of an observation, so it
#' is a density for a continuous response, a probability for a discrete one,
#' and a survival probability for a censored survival time.
#'
#' @param y the outcome, coerced as the family expects.
#' @param weights prior weights.
#' @param eta_draws a list of `H` matrices of draws by observations.
#' @param family_name,link,family_opts the family specification.
#' @param aux a matrix of draws by nuisance parameters, with zero columns when
#'   the family has none.
#' @return A matrix of draws by observations.
#' @keywords internal
.genbart_logdens <- function(y, weights, eta_draws, family_name, link, family_opts, aux) {
    .Call(`_genbart_genbart_logdens`, y, weights, eta_draws, family_name, link, family_opts, aux)
}

#' Score and information of a family, analytic or by differences
#'
#' Exists so that the test suite can check each family's analytic derivatives
#' against central differences of its own log density.
#'
#' @param y,weights,eta_draws,family_name,link,family_opts,aux as for
#'   `.genbart_logdens()`.
#' @param component which additive predictor to differentiate with respect to.
#' @param by_difference use central differences instead of the analytic form.
#' @param blocked evaluate a whole draw at once through the family's block
#'   methods rather than one observation at a time. The two paths should agree;
#'   they differ for a family whose per-observation route falls back on
#'   differences while its block route does not.
#' @return A list with matrices `d1` and `info`, draws by observations.
#' @keywords internal
.genbart_derivs <- function(y, weights, eta_draws, family_name, link, family_opts, aux, component, by_difference, blocked = FALSE) {
    .Call(`_genbart_genbart_derivs`, y, weights, eta_draws, family_name, link, family_opts, aux, component, by_difference, blocked)
}

#' Polya-Gamma draws, for checking the sampler
#' @param n number of draws.
#' @param b,c parameters of the distribution.
#' @return A numeric vector of draws.
#' @keywords internal
.genbart_rpg <- function(n, b, c) {
    .Call(`_genbart_genbart_rpg`, n, b, c)
}

.genbart_rtruncnorm <- function(n, lo, hi) {
    .Call(`_genbart_genbart_rtruncnorm`, n, lo, hi)
}

#' Whether the installed shared library was compiled with optimization
#'
#' Compilers define `__OPTIMIZE__` when they are optimizing, so this is exact
#' rather than a guess. It exists because an unoptimized build of this package
#' is between five and twenty times slower, and nothing else about it looks
#' wrong -- which makes it very easy to spend a long time drawing conclusions
#' from the wrong numbers.
#'
#' @return `TRUE` if the library was optimized.
#' @keywords internal
.genbart_optimized <- function() {
    .Call(`_genbart_genbart_optimized`)
}

