# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fit a generalized BART model
#'
#' The workhorse behind [bartisan()]. Not intended to be called directly: it
#' assumes the design matrix has already been mapped to the unit interval and
#' the response already coerced to the form the requested family expects.
#'
#' @param X a design matrix with entries in `[0, 1]`, possibly with `NA`.
#' @param has_na `logical`; one entry per column of `X` saying whether that
#'   column contains a missing value. A rule on a column with none is not given
#'   a missing-value branch, so complete data reproduces the sampler exactly as
#'   it was.
#' @param y the response, coerced by the calling family.
#' @param weights `numeric`; the prior weights.
#' @param offset an `H` by `N` matrix of fixed contributions to the additive
#'   predictors.
#' @param group_probs a sparse matrix whose columns are predictor groups.
#' @param family_name,link,family_opts the family specification.
#' @param control a list of sampler and prior settings.
#' @returns A list of posterior draws and the encoded forests.
#' @keywords internal
.bartisan_fit <- function(X, has_na, y, weights, offset, group_probs, family_name, link, family_opts, control, random_spec, codes, cat_col, n_levels, vc_basis) {
    .Call(`_bartisan_bartisan_fit`, X, has_na, y, weights, offset, group_probs, family_name, link, family_opts, control, random_spec, codes, cat_col, n_levels, vc_basis)
}

#' Which stored trees split on a given set of predictor columns
#'
#' A sum of trees is separable, so a tree that never splits on a column
#' contributes the same amount however that column is set. Partial dependence
#' evaluates one column over a grid with the rest of the data held fixed, so the
#' trees this marks out are the only ones that have to be re-evaluated at each
#' grid point; the rest are evaluated once.
#'
#' @param forest_flat,tree_start the encoded forests returned by
#'   `.bartisan_fit()`.
#' @param num_forest,num_trees,num_draws `integer`; the dimensions of the
#'   stored chain.
#' @param num_cols `integer`; the zero-based columns of the design matrix to
#'   look for, for rules without a level mask.
#' @param cat_cols `integer`; the zero-based columns of the level-code matrix to
#'   look for, for rules with one.
#' @returns A `logical` vector with one entry per stored tree, in the order the
#'   flat encoding holds them, which is iteration-major and then forest and then
#'   tree.
#' @keywords internal
.bartisan_tree_uses <- function(forest_flat, tree_start, num_forest, num_trees, num_draws, num_cols, cat_cols) {
    .Call(`_bartisan_bartisan_tree_uses`, forest_flat, tree_start, num_forest, num_trees, num_draws, num_cols, cat_cols)
}

#' Evaluate stored forests at new data
#'
#' @param X a design matrix with entries in `[0, 1]`.
#' @param forest_flat,tree_start the encoded forests returned by
#'   `.bartisan_fit()`.
#' @param bandwidth a matrix of per-tree bandwidths.
#' @param num_forest,num_trees,num_draws `integer`; the dimensions of the
#'   stored chain.
#' @param soft `logical`; whether the decision rules are soft.
#' @param gate `integer`; which gate the soft rules use; see `GateShape` in
#'   `node.h`.
#' @param iterations `integer`; the zero-based saved iterations to evaluate.
#' @param codes a matrix of level codes for the categorical rules.
#' @param tree_mask `logical`; one entry per stored tree, in the order
#'   `.bartisan_tree_uses()` reports, saying whether to evaluate it. A
#'   zero-length vector evaluates every tree, which is the ordinary case; a
#'   subset is what partial dependence uses to avoid re-evaluating the trees
#'   that cannot move across its grid.
#' @returns A list of `num_forest` matrices of additive predictors.
#' @keywords internal
.bartisan_predict <- function(X, forest_flat, tree_start, bandwidth, num_forest, num_trees, num_draws, soft, gate, iterations, codes, tree_mask) {
    .Call(`_bartisan_bartisan_predict`, X, forest_flat, tree_start, bandwidth, num_forest, num_trees, num_draws, soft, gate, iterations, codes, tree_mask)
}

#' Conditional log density of the outcome at stored posterior draws
#'
#' Evaluates the family's log density for each observation at each posterior
#' draw of the additive predictors, using the nuisance parameters drawn at the
#' same iteration. This is the likelihood contribution of an observation, so it
#' is a density for a continuous response, a probability for a discrete one,
#' and a survival probability for a censored survival time.
#'
#' @param y the outcome, coerced as the family expects.
#' @param weights `numeric`; the prior weights.
#' @param eta_draws a list of `H` matrices of draws by observations.
#' @param family_name,link,family_opts the family specification.
#' @param aux a matrix of draws by nuisance parameters, with zero columns when
#'   the family has none.
#' @returns A matrix of draws by observations.
#' @keywords internal
.bartisan_logdens <- function(y, weights, eta_draws, family_name, link, family_opts, aux) {
    .Call(`_bartisan_bartisan_logdens`, y, weights, eta_draws, family_name, link, family_opts, aux)
}

#' Category probabilities of a multinomial probit fit, by simulation
#'
#' The probability that the argmax of a correlated Gaussian vector falls in each
#' category is an orthant probability with no closed form, so it is simulated.
#' Fresh draws are taken on every call, which makes the estimate unbiased; the
#' Monte Carlo error is then averaged down by the posterior draws, so a modest
#' number of replicates per draw is enough for a posterior mean.
#'
#' @param eta_draws a list of one draws-by-observations matrix per latent
#'   variable.
#' @param sigma a matrix of draws by the lower triangle of the covariance
#'   matrix, column-major within a row, as `aux` stores it.
#' @param replicates `integer`; the number of simulation replicates per draw
#'   and observation.
#' @returns An array of draws by observations by categories.
#' @keywords internal
.bartisan_mnp_probs <- function(eta_draws, sigma, replicates) {
    .Call(`_bartisan_bartisan_mnp_probs`, eta_draws, sigma, replicates)
}

#' Score and information of a family, analytic or by differences
#'
#' Exists so that the test suite can check each family's analytic derivatives
#' against central differences of its own log density.
#'
#' @param y,weights,eta_draws,family_name,link,family_opts,aux as for
#'   `.bartisan_logdens()`.
#' @param component `integer`; which additive predictor to differentiate with
#'   respect to.
#' @param by_difference `logical`; whether to use central differences rather
#'   than the analytic form.
#' @param blocked `logical`; whether to evaluate a whole draw at once through
#'   the family's block methods rather than one observation at a time. Default
#'   is `FALSE`. The two paths should agree; they differ for a family whose
#'   per-observation route falls back on differences while its block route does
#'   not.
#' @returns A list with matrices `d1` and `info`, draws by observations.
#' @keywords internal
.bartisan_derivs <- function(y, weights, eta_draws, family_name, link, family_opts, aux, component, by_difference, blocked = FALSE) {
    .Call(`_bartisan_bartisan_derivs`, y, weights, eta_draws, family_name, link, family_opts, aux, component, by_difference, blocked)
}

#' Polya-Gamma draws, for checking the sampler
#' @param n `integer`; the number of draws.
#' @param b,c `numeric`; the parameters of the distribution.
#' @returns A numeric vector of draws.
#' @keywords internal
.bartisan_rpg <- function(n, b, c) {
    .Call(`_bartisan_bartisan_rpg`, n, b, c)
}

.bartisan_rtruncnorm <- function(n, lo, hi) {
    .Call(`_bartisan_bartisan_rtruncnorm`, n, lo, hi)
}

#' Whether the installed shared library was compiled with optimization
#'
#' Compilers define `__OPTIMIZE__` when they are optimizing, so this is exact
#' rather than a guess. It exists because an unoptimized build of this package
#' is between five and twenty times slower, and nothing else about it looks
#' wrong, which makes it very easy to spend a long time drawing conclusions
#' from the wrong numbers.
#'
#' @returns `TRUE` if the library was optimized.
#' @keywords internal
.bartisan_optimized <- function() {
    .Call(`_bartisan_bartisan_optimized`)
}

